spring.application.name=crudalumnos
spring.datasource.url=jdbc:mysql://localhost:3306/inserta_matriculas?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Configurar JPA (ddl-auto=update o ddl-auto=create)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Metemos swagger
springdoc.swagger-ui.path=/swagger-ui.html